### ISSUE TITLE
战斗数据字段解析疑惑

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/battle#7]
## AWAYTIME

这个有好几种形式，分别代表什么？

![image](https://user-images.githubusercontent.com/8476969/114767498-48647680-9d9a-11eb-9c4d-400938b84dcd.png)

**Comment by iRuxu** [comment]
## EFFECT_LIST
![image](https://user-images.githubusercontent.com/8476969/114773169-48b44000-9da1-11eb-914a-2ab010160e58.png)
请求解析一个数据的意义

**Comment by iRuxu** [comment]
## 统计信息中的stat含义
![image](https://user-images.githubusercontent.com/8476969/114774979-58348880-9da3-11eb-9bcd-0b56c344fbb5.png)

对应
![image](https://user-images.githubusercontent.com/8476969/114775020-67b3d180-9da3-11eb-9f93-ccafc8c8dfeb.png)

文档含义不明确，请求解析

**Comment by iRuxu** [comment]
## 战斗复盘如何开启
EVERYTHING  = 16, -- 战斗复盘
目前数据内均为空

**Comment by iRuxu** [comment]
## 时间戳相关与文档不符
![image](https://user-images.githubusercontent.com/8476969/114783665-a306ce00-9dac-11eb-8dae-d2bf7c3021ca.png)

**Comment by iRuxu** [comment]
## 天梯榜需求字段
1. 使用玩家名+服务器+时间生成的战斗标识
2. 玩家面板数据
3. 玩家装备数据
4. 玩家奇穴数据
5. 玩家秘籍数据

**Comment by iRuxu** [comment]
## 复盘数据
Everything的开启方式是？
示例数据中和文档对不太上，需要解析

**Comment by IZiki** [comment]
![image](https://user-images.githubusercontent.com/39233273/114808407-c183be00-9dda-11eb-942a-154381fc30d5.png)
